name: Check Secrets

on:
  push:
    branches:
      - main # Change this to your project's main branch

jobs:
  check_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Secrets
        run: |
          echo "AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
