name: Build and Deploy to S3

on:
  push:
    branches:
      - main # Change this to your project's main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Vue.js Project
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v2

        with:
          args: --acl public-read --delete --exclude "node_modules/*" dist/ s3://hamzii-vue-app/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
