name: Deploy to OBS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use Node.js version 14

      - name: Install Dependencies
        run: npm install

      - name: Build Vue.js Project
        run: npm run build

      - name: Download and Install obsutil
        run: |
          wget https://obs-community-intl.obs.ap-southeast-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz
          tar -xzvf obsutil_linux_amd64.tar.gz
          chmod 755 $(ls -d obsutil_linux_amd64*/ | head -n 1)/obsutil
          cd $(ls -d obsutil_linux_amd64*/ | head -n 1)
          ./obsutil version

      - name: Configure obsutil
        run: |
          echo '[Credentials]' > ~/.obsutilconfig
          echo "language=en" >> ~/.obsutilconfig
          echo "ak=${{ secrets.OBS_ACCESS_KEY }}" >> ~/.obsutilconfig
          echo "sk=${{ secrets.OBS_SECRET_KEY }}" >> ~/.obsutilconfig
          echo "endpoint=${{ secrets.OBS_ENDPOINT }}" >> ~/.obsutilconfig
        
      - name: Upload to OBS
        run: |
          $(ls -d obsutil_linux_amd64*/ | head -n 1)/obsutil cp -r ../dist/* obs://${{ secrets.OBS_BUCKET }}
